[tasks.default]
    links = [
        [".tmux.conf", "tmux.conf"],
        [".tmux", "tmux"],
        [".tmuxinator", "tmuxinator"],
        [".zshrc", "zshrc"],
        [".aliases", "aliases"],
        [".vimrc", "vimrc"],
        [".vim", "vim"],
        [".byobu", "byobu"],
        ["bin", "bin"],
    ]


