[tasks.default]
    links = [
        [".zshrc", "zshrc"],
        [".aliases", "aliases"],
        [".vimrc", "vimrc"],
        [".vim", "vim"],
        [".byobu", "byobu"],
        [".zgen-src", "zgen"],
        ["bin", "bin"],
    ]


